### ISSUE TITLE
Blank popup which can't be dismissed when using Unity Debug player

### ISSUE THREAD

**Issue by mwerle** [linuxgurugamer/ToolbarControl#1] opened 2018-06-10 15:12 UTC
Works with the standard player and clicking "Hide this window at startup" stops it popping up in the Debug Player.

But ultimately, as a UTILITY MOD, it should DEFINITELY NOT spam users on startup. Imagine if every mod popped up a tutorial on startup?!  There is already a link to the help when the user clicks on the icon.

(EDIT: Yes, I know I have several mods installed in this screenshot; originally I came across this issue on a new install with no mods except the Kerbal Object Inspector which forces this mod to be installed).

![image](https://user-images.githubusercontent.com/615724/41202665-87d6fdf4-6d07-11e8-9ac5-d106854ccfc1.png)

**Comment by linuxgurugamer** [comment] 2018-06-11 14:58
You have a problem, which is why it's blank.  See all those NullRefs?
Please, before reporting this as a bug, ask for help on the forum.  This is not a bug, or, at least I can't consider it a bug until more investigation.
Many other people are using this without a problem

**Comment by mwerle** [comment] 2018-06-11 15:11
Please see the edit of my post.  This issue also occurred on a brand-new install of KSP having ONLY installed Kerbal Object Inspector and the two dependencies it pulls in, which includes this ToolbarControl.

**This occurs only when using the DEBUG BUILD of the Unity player (2017.1.3p1)**, not the regular binary shipped with the game. Hence I'm not surprised nobody else has seen this issue.
Nevertheless it indicates that these mods are doing something slightly naughty somewhere; sorry, I didn't really have time to investigate further, but from memory there were nullref's just from these mods.

My core point about unnecessary popups stands, whether or not they work as intended.

**Comment by linuxgurugamer** [comment] 2018-06-11 15:44
It's a useless report, unless you provide a log file.
and, I don't use the debug build.  KSP does a nice job of detecting nullrefs.  
It's not a useless popup, it doesn't happen except to you in a build which no one else uses.

**Comment by linuxgurugamer** [comment] 2018-06-11 15:47
The popup is from the intro window, and can be permenantly dismissed by clicking a button.  
Sorry, unless you can reproduce this in standard KSP, it's not a valid report

**Comment by linuxgurugamer** [comment] 2018-06-12 11:51
I'm willing to take a look, how do I run the debug build of Unity?

**Comment by mwerle** [comment] 2018-06-12 13:00
Unfortunately it's a bit involved, but for modders, IMHO, well worth it for debugging/profiling of mods.

I followed @sarbian's instructions in [this thread](https://forum.kerbalspaceprogram.com/index.php?/topic/102909-ksp-plugin-debugging-and-profiling-for-visual-studio-and-monodevelop-on-all-os/) a long time ago. It's still accurate apart from the version of Unity - I updated my environment last weekend.

The Unity version for KSP1.4.3 is 2017.1.3p1 (I've in the past used a slightly different patch version, but it's best to stick with the exact same one. The Visual Studio installer has support for Unity development nowadays but it uses 2017.2; I haven't tried that one).

If you don't have Windows to install Unity on let me know, I can provide the Linux player binaries for Unity (although not entirely sure how legal that would be).

If you decide it's too much bother, I can look into this probably next week.

**Comment by linuxgurugamer** [comment] 2018-06-12 14:33
I develop on Windows, I'll take a look.
In the meantime, if you could provide me with the log file, that would be helpful in tracking down any issues.

**Comment by mwerle** [comment] 2018-06-12 15:01
Here you go; and I just confirmed that those nullrefs you see in the screenshot are due the ToolbarControl mod, although there are various errors before the nullrefs start as well.

I just started from a fresh install, only mod installed is Kerbal Object Inspector + dependencies (via CKAN):

```
Environment Info
Win32NT 7FFFFFFFFFFFFFFF  Args: KSP_x64_Dbg.exe 

Mod DLLs found:
Stock assembly: Assembly-CSharp v0.0.0.0
MiniAVC v1.0.3.2
ClickThroughBlocker v0.1.6.5 / v1.0.0.0
MiniAVC v1.0.3.2
ToolbarControl v0.1.6.9 / v1.0.0.0
MiniAVC v1.0.3.2
KerbalObjectInspector v1.1.6.0 / v1.0.0.0
Stock assembly: KSPSteamCtrlr v0.0.1.35
Stock assembly: Steamworks.NET v9.0.0.0 / v9.0.0

Folders and files in GameData:
000_ClickThroughBlocker
001_ToolbarControl
KerbalObjectInspector
Stock folder: Squad
```

```
[EXC 23:47:27.805] NullReferenceException: Object reference not set to an instance of an object
	ToolbarControl_NS.IntroWindowClass.LoadAndDisplay (System.String f) (at /var/lib/jenkins/workspace/T-Z/ToolbarControl/ToolbarControl/IntroWindow.cs:151)
	ToolbarControl_NS.IntroWindowClass.IntroWindow (Int32 id) (at /var/lib/jenkins/workspace/T-Z/ToolbarControl/ToolbarControl/IntroWindow.cs:191)
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID) (at C:/buildslave/unity/build/Runtime/IMGUI/Managed/GUILayout.cs:497)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, Int32 instanceID, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style) (at C:/buildslave/unity/build/Runtime/IMGUI/Managed/GUI.cs:1836)
```

[KSP_TEST_143-Logs.zip](https://github.com/linuxgurugamer/ToolbarControl/files/2094531/KSP_TEST_143-Logs.zip)

**Comment by linuxgurugamer** [comment] 2018-06-12 15:14
Well, that doesn't make any sense.  This is the line that's generating the error:

 ```
catch (Exception e)
 {
                Log.Error("Load error: " + e.Message);
                return false;
 }

```
Apparently the exception is a null reference, meaning that the message is null.  Which is totally wierd. So, why would an exception have a null?  This doesn't happen in the regular game.  Certainly easy enough to fix, but before I do, I want to understand the following questions:

1. It's trying to load and read this file:
     GameData/001_ToolbarControl/PluginData/Intro.txt
Which is there in the mod, since it displays properly in a regular game.  So why is it not there for you?  Is it possible that the debug version has the base directory in something other than the KSP game directory?

2.  Why is the message null?

**Comment by linuxgurugamer** [comment] 2018-06-12 15:14
I will test it by removing that file to see if it catches the exception properly

**Comment by linuxgurugamer** [comment] 2018-06-12 15:21
So, in a regular install, when I remove the intro file and force it to load at startup, I see the following in the log:

`Toolbarcontrol: Load error: Could not find file "R:\KSP_1.4.3_dev\GameData\001_ToolbarControl\PluginData\Intro.txt".
`

Which is what is generated by catching the exception.  And while blank, the buttons on the window are there and working.  This shows that the "e.Message" is being properly set.

So, I'm still leaning towards something in the debug environment being different.

Comments and/or ideas and/or suggestions?

**Comment by mwerle** [comment] 2018-06-13 00:30
> Comments and/or ideas and/or suggestions?

I agree, that sounds very strange. I don't think it's in-spec that an exception can be null.

Leave it with me; I can hopefully look into it next week. Sorry, but this week I have some real-life deadlines.

**Comment by linuxgurugamer** [comment] 2018-06-13 14:49
Ok.  No rush. RL comes first

**Comment by linuxgurugamer** [comment] 2018-08-01 14:30
Closing since it seems to be only in the debug environment, reopen if you find anything

**Closed as completed by linuxgurugamer** 2018-08-01 14:30 UTC

**Comment by mwerle** [comment] 2018-08-27 17:04
Sorry it went so long; I've been mega-busy IRL.  Just brought mum to the airport today and had some time to play around with KSP again, but it  looks like I now got beaten to the punch in issue #2.

Just to complete the documentation of this issue for future readers, the nullref was ultimately being raised during IntroWindow::OnGUI() because the introWindowId was invalid on line 67.  That's because GetControlID was being called in a class initializer, which is against Unity spec. How exactly that then trickled through into your exception logger called in the try,,catch block of the Load() function and why it works in the non-Debug build of Unity I'm still not entirely clear on, but there's more details in the pull request fixing issue #2.
